Feature#4/creat views
BC-MAY-21-ROR/kata-06-el-reloj-checador-k6-ca-reilero-01 pull request #10
Opened 2022-09-09 23:41 UTC by claunicole

# Description
What did you implemented/Why did you implemented this:
 -Created view of the employees
 -Created view of the company branch
 -Created the check application view in Home
 -Added bootstrap gem 
 -Styled the home view 

 # Testing
 Help me how can I test or look at the changes
-Create a new company branch in rails console, now run rails server and enter the /companies route in your browser, check if you can see the name of the branch.

 ## Screenshots
![Home_view](https://user-images.githubusercontent.com/101293812/189458645-86783289-451f-43c2-a749-329a1ff77289.JPG)

2022-09-12 14:02 UTC, dannharo commented on app/assets/stylesheets/home.scss
> +body {
please sort all properties on your `scss` files

2022-09-12 14:02 UTC, dannharo commented on app/assets/stylesheets/home.scss
> +  background: #4895ef;
uses colors as [variables](https://sass-lang.com/documentation/variables) to make changes easier.

2022-09-12 14:02 UTC, dannharo commented on app/assets/stylesheets/home.scss
> +  background: #4895ef;
I recommend you read about [The 7-1 Pattern](https://sass-guidelin.es/#the-7-1-pattern)
for a better management of your site styles.

2022-09-12 14:02 UTC, dannharo commented on app/views/home/index.html.erb
> +<div>
check indentation here

2022-09-12 14:02 UTC, dannharo commented on app/views/employees/index.html.erb
> +<p>Find me in app/views/employees/index.html.erb</p>
you could avoid this also [here](https://github.com/BC-MAY-21-ROR/kata-06-el-reloj-checador-k6-ca-reilero-01/pull/10/files#diff-4ddbd659dee033dbee675502845ec3de63686d5bf5156f752b5dc39ad5767a06R2)

2022-09-12 14:02 UTC, dannharo commented on app/views/companies/index.html.erb
> +<p><%= company.name %></p>
indentation into the `do` block

2022-09-13 14:52 UTC, dannharo reviewed
looks good, just some minor comments

2022-09-13 14:52 UTC, dannharo commented on app/assets/stylesheets/sass/utils/_colors.scss
> +}
variables ca be defined like just like this:
```
$dark-grey: rgba(0, 18, 25, 0.96);
```

and use it:
```
color: $dark-grey;
```
instead:
```
color: var(--dark-grey);
```

as they mention [here](https://sass-lang.com/documentation/variables)

2022-09-13 14:52 UTC, dannharo commented on app/views/home/index.html.erb
> +<div>
indentation here, in the other files you're using two spaces.

2022-09-13 14:52 UTC, dannharo commented on app/assets/stylesheets/application.css
> +
you could delete these empty lines

2022-09-13 19:34 UTC, YilKanda requested changes
Solve the reviews of @dannharo

2022-09-14 22:10 UTC, claunicole commented on app/assets/stylesheets/home.scss
> +body {
Done

2022-09-14 22:10 UTC, claunicole commented on app/assets/stylesheets/home.scss
> +  background: #4895ef;
Done

2022-09-14 22:10 UTC, claunicole commented on app/views/home/index.html.erb
> +<div>
Done

2022-09-14 22:10 UTC, claunicole commented on app/views/employees/index.html.erb
> +<p>Find me in app/views/employees/index.html.erb</p>
Done

2022-09-14 22:10 UTC, claunicole commented on app/assets/stylesheets/sass/utils/_colors.scss
> +}
Done

2022-09-15 14:21 UTC, dannharo reviewed
check [this file](https://github.com/BC-MAY-21-ROR/kata-06-el-reloj-checador-k6-ca-reilero-01/pull/10/files#diff-70acf32a949fd60a5a3d1ae8bbca9090058a7f011f201c41e6a8b1a51ea12c02R1) indentation, only that, after that ping me to approve it

2022-09-15 17:22 UTC, dannharo commented on app/views/home/index.html.erb
> +</div>
```suggestion
<div>
  <div class= "watch_container">
    <h4 class="h4"> <%= Time.now.strftime("%F")%> </h4>
    <h5 class="h5">Hora <%= Time.now.strftime("%H:%M:%S")%> </h5>
    <div class="form">
      <%= form_for :post do |f| %>
        <%= f.text_field :title, placeholder:'Número privado', class:'text-field'%><br>
        <div class="button-container">
          <%= f.submit 'Check', class:'button'%>
        </div>
      <%end%>
    </div>
  </div>
</div>
```

2022-09-15 17:22 UTC, merged